# Generated by Django 4.0.3 on 2022-09-13 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(default=('FOLDER', 'FILE'), max_length=6)),
                ('size', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parentId', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_management_app.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parentId',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
