# Generated by Django 4.0.3 on 2022-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0002_item_remove_folder_parentid_delete_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parentId',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.CharField(default='aa', max_length=255),
            preserve_default=False,
        ),
    ]
