# Generated by Django 4.0.3 on 2022-09-13 12:35

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0003_remove_item_parentid_item_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parentId',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_management_app.item'),
        ),
    ]
