# Generated by Django 4.0.3 on 2022-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0004_item_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parentId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
