# Generated by Django 4.0.3 on 2022-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0005_alter_item_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tree_id',
        ),
    ]
