# Generated by Django 4.0.3 on 2022-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0006_import_remove_item_level_remove_item_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
