# Generated by Django 4.0.3 on 2022-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0007_alter_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='parentId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
