# Generated by Django 4.0.3 on 2022-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0008_alter_item_parent_alter_item_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='items',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
