# Generated by Django 4.0.3 on 2022-09-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0009_import_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='items',
        ),
    ]
